AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - test/**/*
Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*
Style/ClassAndModuleChildren:
  Exclude:
    - fixtures/**/*
